//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMining.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMining.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date,Open,High,Low,Close,Adj Close,Volume
        ///1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
        ///1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
        ///1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
        ///1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
        ///1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
        ///1980-12-19,0.126116,0.126674,0.126116,0.126116,0.098578,48630400
        ///1980-12-22,0.132254,0.132813,0.132254,0.132254,0.103376,37363200
        ///1980-12-23,0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string AAPL {
            get {
                return ResourceManager.GetString("AAPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,date,open,high,low,close,volume
        ///0,2014-06-04 07:00:00,1546.7,1546.8,1163.0,1170.0,35146
        ///1,2014-06-05 07:00:00,1187.3,1195.0,1141.1,1145.1,24974
        ///2,2014-06-06 07:00:00,1158.3,1173.5,1151.0,1163.0,7889
        ///3,2014-06-09 07:00:00,1178.9,1185.6,1155.7,1172.1,7304
        ///4,2014-06-10 07:00:00,1178.9,1181.0,1160.1,1170.0,3216
        ///5,2014-06-11 07:00:00,1175.0,1183.0,1157.1,1179.9,8837
        ///6,2014-06-12 07:00:00,1175.0,1183.0,1157.1,1179.9,8837
        ///7,2014-06-13 07:00:00,1175.0,1183.0,1157.1,1179.9,8837
        ///8,2014-06-16 07:00:00,1164.0,1181.2,1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string yandex_1day {
            get {
                return ResourceManager.GetString("yandex_1day", resourceCulture);
            }
        }
    }
}
